[hugoVersion]
extended = false
min = "0.56.0"

[[mounts]]
source = "assets/scss/_debugprint.scss"
target = "assets/scss/_debugprint.scss"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "data"
target = "data"
