ignoreErrors = ["dnb-sample-error"]

[dnb.debug]
loglink = "https://dnbql.netlify.app/log"
namespace = "dnb"
debuglevel = 8
development = true

[dnb.debug.plugins]
scss = [
  "scss/_debugprint.scss"
]


[[dnb.debug.formatters]]
type = "int"
class = "flat"
slug = "int"
label = "Integer"
description = "a positive or negative number without a floating point"

[[dnb.debug.formatters]]
type = "*page.Pager"
class = "struct"
slug = "pager"
label = "Pagination Object"
description = "an object containing pagination information for the current page"

[[dnb.debug.formatters]]
type = "text.Position"
class = "struct"
slug = "position"
label = "Position Object"
description = "an object containing position information for the current line in a shortcode"

