[module.hugoVersion]
extended = false
min = "0.56.0"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "data/dnb/debugprint"
target = "data/dnb/debugprint"

[[module.mounts]]
source = "layouts"
target = "layouts"
