baseURL = "https://davidsneighbour.github.io/hugo-debug/"

# disabling unused features
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT"]

[[module.imports]]
path = "github.com/davidsneighbour/hugo-debug"

[[module.imports]]
path = "github.com/davidsneighbour/hugo-hooks"
